Repository radionets-project/radionets, pull requests merged in 2025-08, with the labels that each got.

#189 Fix changelog
  CHANGES.rst
Labels: no-changelog-needed

#192 Complex layers
  docs/changes/192.feature.rst
  src/radionets/architecture/layers.py
  tests/test_architecture_layers.py
Labels: enhancement

#193 Set logging level to INFO as default, get rid of DEBUG output
  docs/changes/193.optimization.rst
  src/radionets/core/callbacks.py
  src/radionets/core/logging.py
  src/radionets/core/model.py
  src/radionets/evaluation/jets.py
  src/radionets/evaluation/scripts/start_evaluation.py
  src/radionets/evaluation/train_inspection.py
  src/radionets/plotting/inspection.py
  src/radionets/training/utils.py
Labels: enhancement, fix

#196 Remove tight_layout in plotting module
  docs/changes/196.maintenance.rst
  src/radionets/plotting/visualization.py
Labels: bug, fix
